name: deploy

on:
  push:
    branches: [master]
  repository_dispatch:
    types: deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: cp ./src/config.devnet.tsx ./src/config.tsx
      - run: npm install
      - run: npm run build
        env:
          CI: false
